// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo5qgvMaNE28B5ZTvF2Wa07O3NvCRiCgQ',
    appId: '1:290586834683:web:6978169073d281af7be25e',
    messagingSenderId: '290586834683',
    projectId: 'trained-gym-trainer-79726',
    authDomain: 'trained-gym-trainer-79726.firebaseapp.com',
    storageBucket: 'trained-gym-trainer-79726.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjgUPVqYShTOU5HEV3TrWRvCyWUFEABEU',
    appId: '1:290586834683:android:6dca2e3fe17026157be25e',
    messagingSenderId: '290586834683',
    projectId: 'trained-gym-trainer-79726',
    storageBucket: 'trained-gym-trainer-79726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-sXYTc4f7O-fnZNg18BIB6kwTmPJLyw',
    appId: '1:290586834683:ios:c409ca029a81d5c57be25e',
    messagingSenderId: '290586834683',
    projectId: 'trained-gym-trainer-79726',
    storageBucket: 'trained-gym-trainer-79726.appspot.com',
    iosBundleId: 'com.example.trainerTrained',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-sXYTc4f7O-fnZNg18BIB6kwTmPJLyw',
    appId: '1:290586834683:ios:30602dfc3b8acaa67be25e',
    messagingSenderId: '290586834683',
    projectId: 'trained-gym-trainer-79726',
    storageBucket: 'trained-gym-trainer-79726.appspot.com',
    iosBundleId: 'com.example.trainerTrained.RunnerTests',
  );
}
